/**
 * Route Mappings
 * (sails.config.routes)
 *
 * Your routes tell Sails what to do each time it receives a request.
 *
 * For more information on configuring custom routes, check out:
 * https://sailsjs.com/anatomy/config/routes-js
 */

module.exports.routes = {

  /***************************************************************************
   *                                                                          *
   * HEALTH CHECK ROUTE                                                       *
   *                                                                          *
   ***************************************************************************/
  'GET /': function (req, res) {
    return res.json({ 
      status: 'OK',
      message: 'Backend server is running',
      timestamp: new Date().toISOString()
    });
  },

  'GET /api/v1/health': function (req, res) {
    return res.json({ 
      status: 'OK',
      message: 'API is healthy',
      timestamp: new Date().toISOString()
    });
  },

  /***************************************************************************
   *                                                                          *
   * AUTHENTICATION ROUTES                                                    *
   *                                                                          *
   ***************************************************************************/
  'POST /api/v1/auth/register': 'AuthController.register',
  'POST /api/v1/auth/login': 'AuthController.login',
  'POST /api/v1/auth/logout': 'AuthController.logout',
  'GET /api/v1/auth/me': 'AuthController.me',

  /***************************************************************************
   *                                                                          *
   * OTHER ROUTES (News, Services, Banks, Sliders, Menus, Users)            *
   * Auto-generated by Sails Blueprints at /api/v1/[modelname]              *
   *                                                                          *
   * Examples:                                                                *
   * GET    /api/v1/news          -> Find all news                           *
   * GET    /api/v1/news/:id      -> Find one news by ID                     *
   * POST   /api/v1/news          -> Create new news                         *
   * PUT    /api/v1/news/:id      -> Update news                             *
   * DELETE /api/v1/news/:id      -> Delete news                             *
   *                                                                          *
   ***************************************************************************/

};
